name = "OptiRise"
author = "NightLighter423"
version = "1.9+1.16.5-fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15ec18ffdf1baf564f536a4c32d73d534351e0978d5b39e6bfcc5ff185e9e466"

[versions]
fabric = "0.16.5"
minecraft = "1.16.5"
