name = "OptiRise"
author = "NightLighter423"
version = "1.8+1.16.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1bd145cc95003a648f9fa3a6047d40c0dc38879652255c5aee7f13a32e9292f"

[versions]
fabric = "0.15.11"
minecraft = "1.16.5"
