name = "OptiRise"
author = "NightLighter423"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8249604d3bda1f3242b13716226e9d8220518d5feb48675b41ea622c5537de39"

[versions]
fabric = "0.15.9"
minecraft = "1.16.5"
